title: Vindhya Vaasini Mallapuram
logo: /profile.png
description: Welcome to my data science portfolio! I'm Vindhya Vaasini Mallapuram, a data science enthusiast with expertise in Machine Learning, Artificial Intelligence, and Data Engineering. Explore my projects showcasing real-world applications of AI and analytics.
show_downloads: true
theme: jekyll-theme-midnight
#remote_theme: pages-themes/leap-day@v0.2.0
#plugins: - jekyll-remote-theme 
# add this line to the plugins list if you already have one
