title: Vindhya Vaasini Mallapuram
logo: image
description: Welcome to my data science portfolio! I'm Vindhya Vaasini Mallapuram, a data science enthusiast with expertise in Machine Learning, Artificial Intelligence, and Data Engineering. Explore my projects showcasing real-world applications of AI and analytics.
show_downloads: true
theme: jekyll-theme-modernist
