otitle: Vindhya Vaasini Mallapuram
logo: /profile_1.png
description: Hello! I'm Vindhya Vaasini Mallapuram, a data science enthusiast. Explore my projects showcasing real-world applications of machine learning, AI and analytics.
show_downloads: false
theme: jekyll-theme-minimal
#remote_theme: pages-themes/leap-day@v0.2.0
#plugins: - jekyll-remote-theme 
# add this line to the plugins list if you already have one
